### PR TITLE
fix: Allow tags and owners for private AMIs

### LINKED ISSUE #5013: Private AMI selection by tag? Or "owner" cannot be set with "tags"
### Description

**Observed Behavior**:

I'm trying to create `EC2NodeClass` and select AMIs by tags. But AMIs are shared by other AWS account.

  amiSelectorTerms:
    - tags:
        tag_key1: tag_value
        tag_key1: tag_value
      owner: "123456789"

But `validation failed: "owner" cannot be set with "tags" in:`
If I omit `owner` , `"no amis exist given constraints"` what is true, because AMIs are not `self,amazon`

**Expected Behavior**:

Ability to select privately shared AMIs by tags.

**Reproduction Steps** (Please include YAML):

  amiSelectorTerms:
    - tags:
        tag_key1: tag_value
        tag_key1: tag_value
      owner: "123456789"

**Versions**:
- Chart Version: v0.32.1
- Kubernetes Version (`kubectl version`): 1.23

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by engedaam**
Fixes #5013 

**Description**
- Karpenter should allow tags and owner to be placed for `amiSelectorTerm` for shared AMIs between accounts.

**How was this change tested?**
- Manually tested

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/apis/v1beta1/ec2nodeclass_validation_cel_test.go [hunk 1]
```diff
@@ -353,6 +353,17 @@ var _ = Describe("CEL/Validation", func() {
 			}
 			Expect(env.Client.Create(ctx, nc)).To(Succeed())
 		})
+		It("should succeed  when an ami selector term has an owner key with tags", func() {
```
Comment (njtran) [inline pkg/apis/v1beta1/ec2nodeclass_validation_cel_test.go:356]: extra space nit
```suggestion
		It("should succeed when an ami selector term has an owner key with tags", func() {
```

File: pkg/providers/amifamily/ami.go [hunk 2]
```diff
@@ -246,13 +246,17 @@ func GetFilterAndOwnerSets(terms []v1beta1.AMISelectorTerm) (res []FiltersAndOwn
 			idFilter.Values = append(idFilter.Values, aws.String(term.ID))
 		default:
 			elem := FiltersAndOwners{
-				Owners: lo.Ternary(term.Owner != "", []string{term.Owner}, []string{"self", "amazon"}),
+				Owners: lo.Ternary(term.Owner != "", []string{term.Owner}, []string{}),
 			}
 			if term.Name != "" {
+				elem = FiltersAndOwners{
+					Owners: lo.Ternary(term.Owner != "", []string{term.Owner}, []string{"self", "amazon"}),
+				}
```
Comment (njtran) [inline pkg/providers/amifamily/ami.go:254]: Since this is only added in for name now, can you add a comment here so that future users know not to remove this because of a security issue?

File: pkg/providers/amifamily/ami_test.go [hunk 3]
```diff
@@ -304,10 +304,7 @@ var _ = Describe("AMIProvider", func() {
 							Values: aws.StringSlice([]string{"my-ami"}),
 						},
 					},
-					Owners: []string{
-						"amazon",
-						"self",
-					},
+					Owners: []string{},
```
Comment (njtran) [inline pkg/providers/amifamily/ami_test.go:307]: nit : Probably can change the name of the test to be more deliberate that we're expecting "empty owners" rather than inferring that the default is empty

**Review by njtran — APPROVED** [review]

File: pkg/providers/amifamily/ami_test.go [hunk 4]
```diff
@@ -287,7 +287,7 @@ var _ = Describe("AMIProvider", func() {
 		})
 	})
 	Context("AMI Selectors", func() {
-		It("should have default owners and use tags when prefixes aren't set", func() {
```
Comment (tzneal) [inline pkg/providers/amifamily/ami_test.go:290]: Can we put some comments on why this is safe? E.g. a link to https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html#tag-restrictions and the quote "When you tag public or shared resources, the tags you assign are available only to your AWS account; no other AWS account will have access to those tags" and that this is ok since the AMI we discover via tags here will only be found if the account owner doing the query has tagged it.

File: website/content/en/preview/concepts/nodeclasses.md [hunk 5]
```diff
@@ -338,7 +338,7 @@ spec:
...
+AMISelectorTerms are used to configure custom AMIs for Karpenter to use, where the AMIs are discovered through ids, owners, name, and [tags](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Using_Tags.html). This field is optional, and Karpenter will use the latest EKS-optimized AMIs for the AMIFamily if no amiSelectorTerms are specified. To select an AMI by name, use the `name` field in the selector term. To select an AMI by id, use the `id` field in the selector term. To ensure that AMIs are owned by the expected owner, use the `owner` field - you can use a combination of account aliases (e.g. `self` `amazon`, `your-aws-account-name`) and account IDs. If this is not set for `name`, it defaults to `self,amazon`.
```
Comment (tzneal) [inline website/content/en/preview/concepts/nodeclasses.md:341]: might add at the end "defaults to `self,amazon` to prevent selecting an AMI that is owned by a different account inadvertently.

Should also cover here why its ok to select by tags and not specify an owner.

**Review by njtran — APPROVED** [review]

**Review by engedaam — COMMENTED** [review]
/karpenter snapshot
