### PR TITLE
test: replaced offsets with GinkgoHelper()

### LINKED ISSUE #4189: Convert all `Expect...` test expectations to use `GingkoHelper`
### Description

Ginkgo offers the function called [`GinkgoHelper`](https://onsi.github.io/ginkgo/#:~:text=Instead%20of%20managing%20offsets%20you%20can%20use%20GinkgoHelper()) which means that you don't have to use the provided `...WithOffset` functions and can instead use this function to get the correct stack trace. We should convert all of our test expectation functions that use this function to use `GingkoHelper()`.

### Relevant Codepaths

1. https://github.com/aws/karpenter/blob/main/test/pkg/environment/aws/expectations.go
2. https://github.com/aws/karpenter/blob/main/test/pkg/environment/common/expectations.go

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by sadath-12**
Fixes #4189 

**Description**

We allow the stack tracing to be handled directly by GinkgoHelper() as we did in https://github.com/aws/karpenter-core/pull/578 instead of doing it manually by offset approach

**How was this change tested?**

```make presubmit```

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/providers/launchtemplate/suite_test.go [hunk 1]
```diff
@@ -120,9 +120,9 @@ func ExpectLaunchTemplatesCreatedWithUserDataContaining(substrings ...string) {
 	Expect(awsEnv.EC2API.CalledWithCreateLaunchTemplateInput.Len()).To(BeNumerically(">=", 1))
 	awsEnv.EC2API.CalledWithCreateLaunchTemplateInput.ForEach(func(input *ec2.CreateLaunchTemplateInput) {
 		userData, err := base64.StdEncoding.DecodeString(*input.LaunchTemplateData.UserData)
-		ExpectWithOffset(2, err).To(BeNil())
```
Comment (jonathan-innis) [inline pkg/providers/launchtemplate/suite_test.go:123]: We need these offsets here since this ForEach is actually double nested due to the function itself as well as the function that is called here. I didn't find a good way to do this with `GinkgoHelper` so I think the current approach is reasonable.

File: pkg/providers/launchtemplate/suite_test.go [hunk 2]
```diff
@@ -132,9 +132,9 @@ func ExpectLaunchTemplatesCreatedWithUserDataNotContaining(substrings ...string)
...
```
Comment (jonathan-innis) [inline pkg/providers/launchtemplate/suite_test.go:135]: Same comment here

File: pkg/providers/launchtemplate/suite_test.go [hunk 3]
```diff
@@ -132,9 +132,9 @@ func ExpectLaunchTemplatesCreatedWithUserDataNotContaining(substrings ...string)
...
+		Expect(err).To(BeNil())
 		for _, substring := range substrings {
-			ExpectWithOffset(2, string(userData)).ToNot(ContainSubstring(substring))
```
Comment (jonathan-innis) [inline pkg/providers/launchtemplate/suite_test.go:137]: And here

File: test/pkg/environment/common/expectations.go [hunk 4]
```diff
@@ -326,35 +327,35 @@ func (env *Environment) ExpectPodsMatchingSelector(selector labels.Selector) []*
...
-}
 
-func (env *Environment) EventuallyExpectNotFoundAssertion(objects ...client.Object) AsyncAssertion {
-	return env.EventuallyExpectNotFoundAssertionWithOffset(1, objects...)
-}
 
-func (env *Environment) EventuallyExpectNotFoundAssertionWithOffset(offset int, objects ...client.Object) AsyncAssertion {
-	return EventuallyWithOffset(offset, func(g Gomega) {
+func (env *Environment) EventuallyExpectNotFoundAssertion(objects ...client.Object) AsyncAssertion {
+	GinkgoHelper()
```
Comment (jonathan-innis) [inline test/pkg/environment/common/expectations.go:357]: Does this need a `GingkgoHelper` since there are no `To()` or `Should()` calls here? This just returns the assertion back to the caller

**Review by jonathan-innis — COMMENTED** [review]
Nice work 🎉

**Comment by sadath-12** [comment]
Thanks for taking time and reviewing @jonathan-innis  , Please have a look at changes .

File: test/pkg/environment/common/expectations.go (hunk 4 above)
Comment (jonathan-innis) [reply test/pkg/environment/common/expectations.go:357]: Looks like you didn't pull this out but still resolved this convo. I still think that you need to drop the `GinkgoHelper()` call here

**Comment by sadath-12** [comment]
Thanks for taking time and reviewing @jonathan-innis , Please have a look at changes .

**Review by jonathan-innis — DISMISSED** [review]
LGTM 🚀

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀
