### PR TITLE
fix: Parsing Selector IDs and Names with spaces

### LINKED ISSUE #4738: Karpenter 0.31.0 can't create new node.
### Description

**Observed Behavior**:
getting this error on v0.31.0
```
karpenter-5dd479847d-kk6v6 controller 2023-10-02T06:57:48.315Z	ERROR	controller.provisioner	Could not schedule pod, incompatible with provisioner "monitoring", daemonset overhead={"cpu":"655m","memory":"628000Ki","pods":"7"}, no instance type satisfied resources {"cpu":"755m","memory":"1037600Ki","pods":"8"} and requirements karpenter.k8s.aws/instance-category In [c m r], karpenter.k8s.aws/instance-encryption-in-transit-supported In [true], karpenter.k8s.aws/instance-generation Exists >2, karpenter.sh/capacity-type In [on-demand spot], karpenter.sh/provisioner-name In [monitoring], kubernetes.io/arch In [amd64 arm64], kubernetes.io/os In [linux], nodetype In [monitoring], provisioner In [monitoring], topology.kubernetes.io/zone In [us-east-1d], type In [karpenter] (no instance type met the scheduling requirements or had a required offering); incompatible with provisioner "system", daemonset overhead={"cpu":"655m","memory":"628000Ki","pods":"7"}, did not tolerate CriticalAddonsOnly=true:NoSchedule; incompatible with provisioner "bitbucket", daemonset overhead={"cpu":"655m","memory":"628000Ki","pods":"7"}, did not tolerate bitbucket=true:NoSchedule; incompatible with provisioner "default", daemonset overhead={"cpu":"655m","memory":"628000Ki","pods":"7"}, did not tolerate default=true:NoSchedule	{"commit": "322822a", "pod": "monitoring/alertmanager-0"}
```

CRDs are installed from version 0.31.0. For some reason it can't find any instances.

**Expected Behavior**:
v0.30.0
```
karpenter-849c9cff87-tchft controller 2023-10-02T07:05:08.818Z	INFO	controller.provisioner	created machine	{"commit": "637a642", "provisioner": "monitoring", "machine": "monitoring-9zpps", "requests": {"cpu":"3955m","memory":"23108896Ki","pods":"10"}, "instance-types": "c5a.4xlarge, c5a.8xlarge, c5ad.4xlarge, c5ad.8xlarge, c5n.4xlarge and 95 other(s)"}
```

**Reproduction Steps** (Please include YAML):
Install v0.31.0. Here is my provisioner and node configs:
```
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: bottlerocket
spec:
  blockDeviceMappings:
    - deviceName: /dev/xvdb
      ebs:
        volumeType: gp3
        volumeSize: 40Gi
        deleteOnTermination: true
  amiFamily: Bottlerocket
  instanceProfile: ${iam-instance-profile-id}
  subnetSelector:
    aws-ids: "${aws-ids}"
  securityGroupSelector:
    karpenter.sh/discovery/${eks-cluster-id}: "${eks-cluster-id}"
  metadataOptions: # require IMDSv2
    httpEndpoint: enabled
    httpProtocolIPv6: disabled
    httpPutResponseHopLimit: 1
    httpTokens: required
```
```
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: monitoring
spec:
  requirements:
    - key: "topology.kubernetes.io/zone"
      operator: In
      values: [${azs}]
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot", "on-demand"]
    - key: "kubernetes.io/arch"
      operator: In
      values: ["arm64", "amd64"]
    - key: "karpenter.k8s.aws/instance-encryption-in-transit-supported"
      operator: In
      values: ["true"]
  kubeletConfiguration:
    containerRuntime: containerd
    systemReserved:
      cpu: 100m
      memory: 100Mi
      ephemeral-storage: 1Gi
    kubeReserved:
      cpu: 200m
      memory: 100Mi
      ephemeral-storage: 3Gi
  limits:
    resources:
      cpu: 100
      memory: 400Gi
  providerRef:
    name: bottlerocket
  labels:
    type: karpenter
    nodetype: monitoring
    provisioner: monitoring
  taints:
    - key: monitoring
      value: "true"
      effect: NoSchedule
  ttlSecondsUntilExpired: 604800
  consolidation:
    enabled: true

```

**Versions**:
- Chart Version: 0.31.0
- Kubernetes Version (`kubectl version`): `Client Version: v1.28.2
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.1-eks-43840fb`

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by engedaam**
Fixes #4738
 
**Description**
- Karpenter should still support the comma-delimited list with spaces in it. , this config works with karpenter <v0.31:
```
  subnetSelector:
    aws-ids: subnet-123, subnet-456, subnet-789
```

**How was this change tested?**
- Manually tested

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates 
- [ ] Yes, issue opened: # 
- [x] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/utils/nodeclass/nodeclass.go [hunk 1]
```diff
@@ -72,7 +72,7 @@ func NewSubnetSelectorTerms(subnetSelector map[string]string) (terms []v1beta1.S
 	for k, v := range subnetSelector {
 		switch k {
 		case "aws-ids", "aws::ids":
-			ids = strings.Split(strings.Trim(v, " "), ",")
+			ids = strings.Split(strings.Replace(v, " ", "", -1), ",")
```
Comment (njtran) [inline pkg/utils/nodeclass/nodeclass.go:75]: Shouldn't we just do the ReplaceAll instead https://pkg.go.dev/strings#ReplaceAll

File: pkg/providers/amifamily/ami.go [hunk 2]
```diff
@@ -263,7 +262,7 @@ func GetFilterAndOwnerSets(terms []v1beta1.AMISelectorTerm) (res []FiltersAndOwn
 				} else {
 					elem.Filters = append(elem.Filters, &ec2.Filter{
 						Name:   aws.String(fmt.Sprintf("tag:%s", k)),
-						Values: aws.StringSlice(functional.SplitCommaSeparatedString(v)),
```
Comment (njtran) [inline pkg/providers/amifamily/ami.go:266]: Wondering how this doesn't catch the bug: 
Looks like we should be trimming each value delimited by the commas. 
```
// SplitCommaSeparatedString splits a string by commas, removes whitespace, and returns
// a slice of strings
func SplitCommaSeparatedString(value string) []string {
	var result []string
	for _, value := range strings.Split(value, ",") {
		result = append(result, strings.TrimSpace(value))
	}
	return result
}
```

File: pkg/utils/nodeclass/suite_test.go [hunk 3]
```diff
@@ -181,7 +181,7 @@ var _ = Describe("NodeClassUtils", func() {
 	})
 	It("should convert a AWSNodeTemplate to a EC2NodeClass (with AMISelector name and owner values set)", func() {
 		nodeTemplate.Spec.AMISelector = map[string]string{
-			"aws::name":   "ami-name1,ami-name2",
+			"aws::name":   "ami-name1,ami-name2, ami-name3",
```
Comment (njtran) [inline pkg/utils/nodeclass/suite_test.go:184]: I would expect this should require a change further down in the test when you check the amiselector terms, but I don't see a change.

File: pkg/utils/nodeclass/suite_test.go [hunk 4]
```diff
@@ -247,6 +247,74 @@ var _ = Describe("NodeClassUtils", func() {
...
+			Expect(nodeClass.Labels).To(HaveKeyWithValue(k, v))
+		}
+		Expect(nodeClass.Spec.SubnetSelectorTerms).To(HaveLen(1))
+		Expect(nodeClass.Spec.SubnetSelectorTerms[0].Tags).To(Equal(nodeTemplate.Spec.SubnetSelector))
+		Expect(nodeClass.Spec.SecurityGroupSelectorTerms).To(HaveLen(1))
+		Expect(nodeClass.Spec.SecurityGroupSelectorTerms[0].Tags).To(Equal(nodeTemplate.Spec.SecurityGroupSelector))
+
+		// Expect AMISelectorTerms to be exactly what we would expect from the filtering above
+		Expect(nodeClass.Spec.AMISelectorTerms).To(HaveLen(6))
+		Expect(nodeClass.Spec.AMISelectorTerms).To(ConsistOf(
```
Comment (njtran) [inline pkg/utils/nodeclass/suite_test.go:270]: Shouldn't there be 9 terms?

File: pkg/utils/nodeclass/suite_test.go [hunk 5]
```diff
@@ -279,6 +347,10 @@ var _ = Describe("NodeClassUtils", func() {
 				ID:   "ami-custom-id",
 				Tags: map[string]string{},
 			},
+			v1beta1.AMISelectorTerm{
+				ID:   "ami-test",
```
Comment (njtran) [inline pkg/utils/nodeclass/suite_test.go:351]: You're not adding this in the beginning, and also the previous line expects this to have len = 3, so I don't think this  test should ever succeed.

File: pkg/utils/nodeclass/suite_test.go (hunk 4 above)
Comment (engedaam) [reply pkg/utils/nodeclass/suite_test.go:270]: Mistakenly, left from testing

File: pkg/utils/nodeclass/suite_test.go (hunk 5 above)
Comment (engedaam) [reply pkg/utils/nodeclass/suite_test.go:351]: Should be 6, mistakenly, left from testing

File: pkg/utils/nodeclass/suite_test.go [hunk 6]
```diff
@@ -247,6 +247,74 @@ var _ = Describe("NodeClassUtils", func() {
 		ExpectSecurityGroupStatusEqual(nodeTemplate.Status.SecurityGroups, nodeClass.Status.SecurityGroups)
 		ExpectAMIStatusEqual(nodeTemplate.Status.AMIs, nodeClass.Status.AMIs)
 	})
+	It("should convert a AWSNodeTemplate to a EC2NodeClass (with AMISelector name and owner values set) with spaces", func() {
```
Comment (njtran) [inline pkg/utils/nodeclass/suite_test.go:250]: This is probably going to get removed soon anyways, since we removed the v1alpha1 controllers/utils for now. Maybe better lived in the karpenter-convert tests?

Comment (engedaam) [reply pkg/utils/nodeclass/suite_test.go:250]: I was thinking this would be for the karpenter internal conversion, and I'm not sure if this would apply after we remove v1alpha1

File: pkg/utils/nodeclass/nodeclass.go [hunk 7]
```diff
@@ -72,7 +72,7 @@ func NewSubnetSelectorTerms(subnetSelector map[string]string) (terms []v1beta1.S
 	for k, v := range subnetSelector {
 		switch k {
 		case "aws-ids", "aws::ids":
-			ids = strings.Split(strings.Trim(v, " "), ",")
+			ids = strings.Split(strings.ReplaceAll(v, " ", ""), ",")
```
Comment (jonathan-innis) [inline pkg/utils/nodeclass/nodeclass.go:75]: This trims spaces from the middle, which I don't think is what we want here. I'd prefer that we just split and then trim the whitespace off the ends of the result elements in the array

**Review by jonathan-innis — COMMENTED** [review]
Are we planning to disallow the CDL in tags for beta with this PR as well? If so, we should add that change in here

File: pkg/utils/nodeclass/nodeclass.go (hunk 7 above)
Comment (jonathan-innis) [reply pkg/utils/nodeclass/nodeclass.go:75]: Also, since this change with white spaces in the middle of values wasn't caught here, I'd like to see us having a functional test for that scenario. 

I doubt many users are putting spaces in the middle of their values or tags, but (if they are), this change would break them

File: pkg/utils/nodeclass/nodeclass.go [hunk 8]
```diff
@@ -97,7 +97,7 @@ func NewSecurityGroupSelectorTerms(securityGroupSelector map[string]string) (ter
 	for k, v := range securityGroupSelector {
 		switch k {
 		case "aws-ids", "aws::ids":
-			ids = strings.Split(strings.Trim(v, " "), ",")
+			ids = functional.SplitCommaSeparatedString(v)
```
Comment (jonathan-innis) [inline pkg/utils/nodeclass/nodeclass.go:100]: Do we need to build this logic into a bespoke function or is it sufficient to do the following that way all of the logic is there

```go
ids = lo.Map(strings.Split(v, ","), func(s string, _ int) string { return strings.Trim(s, " ") }
```

Comment (jonathan-innis) [reply pkg/utils/nodeclass/nodeclass.go:100]: I could also see the helper function live inside of this file. I'm a bit unconvinced that we need a project-wide helper for this specific logic

File: pkg/providers/launchtemplate/suite_test.go [hunk 9]
```diff
@@ -1627,7 +1627,7 @@ var _ = Describe("LaunchTemplates", func() {
 		})
 		Context("Subnet-based Launch Template Configration", func() {
 			It("should explicitly set 'AssignPublicIPv4' to false in the Launch Template", func() {
-				nodeClass.Spec.SubnetSelectorTerms = []v1beta1.SubnetSelectorTerm{{Tags: map[string]string{"Name": "test-subnet-1,test-subnet-3"}}}
+				nodeClass.Spec.SubnetSelectorTerms = []v1beta1.SubnetSelectorTerm{{Tags: map[string]string{"Name": "test-subnet-1"}}}
```
Comment (jonathan-innis) [inline pkg/providers/launchtemplate/suite_test.go:1630]: Consider creating multiple terms here for the name tag?

File: pkg/utils/nodeclass/nodeclass.go [hunk 10]
```diff
@@ -124,11 +124,11 @@ func NewAMISelectorTerms(amiSelector map[string]string) (terms []v1beta1.AMISele
...
-			ids = strings.Split(strings.Trim(v, " "), ",")
+			ids = lo.Map(strings.Split(v, ","), func(s string, _ int) string { return strings.Trim(s, " ") })
 		case "aws::name":
-			names = strings.Split(strings.Trim(v, " "), ",")
+			names = lo.Map(strings.Split(v, ","), func(s string, _ int) string { return strings.Trim(s, " ") })
 		case "aws::owners":
-			owners = strings.Split(strings.Trim(v, " "), ",")
+			owners = lo.Map(strings.Split(v, ","), func(s string, _ int) string { return strings.Trim(s, " ") })
 		default:
 			tags[k] = v
```
Comment (jonathan-innis) [inline pkg/utils/nodeclass/nodeclass.go:133]: Based on the changes that you've made, we now need to split the tag value here if it contains a comma

File: pkg/utils/nodeclass/nodeclass.go [hunk 11]
```diff
@@ -97,7 +97,7 @@ func NewSecurityGroupSelectorTerms(securityGroupSelector map[string]string) (ter
 	for k, v := range securityGroupSelector {
 		switch k {
 		case "aws-ids", "aws::ids":
-			ids = strings.Split(strings.Trim(v, " "), ",")
+			ids = lo.Map(strings.Split(v, ","), func(s string, _ int) string { return strings.Trim(s, " ") })
 		default:
 			tags[k] = v
```
Comment (jonathan-innis) [inline pkg/utils/nodeclass/nodeclass.go:102]: Based on the changes that you've made, we now need to split the tag value here if it contains a comma

File: pkg/utils/nodeclass/nodeclass.go [hunk 12]
```diff
@@ -72,7 +72,7 @@ func NewSubnetSelectorTerms(subnetSelector map[string]string) (terms []v1beta1.S
 	for k, v := range subnetSelector {
 		switch k {
 		case "aws-ids", "aws::ids":
-			ids = strings.Split(strings.Trim(v, " "), ",")
+			ids = lo.Map(strings.Split(v, ","), func(s string, _ int) string { return strings.Trim(s, " ") })
 		default:
 			tags[k] = v
```
Comment (jonathan-innis) [inline pkg/utils/nodeclass/nodeclass.go:77]: Based on the changes that you've made, we now need to split the tag value here if it contains a comma

**Review by jonathan-innis — COMMENTED** [review]
A few comments

File: pkg/utils/nodeclass/suite_test.go (hunk 6 above)
Comment (jonathan-innis) [inline pkg/utils/nodeclass/suite_test.go:250]: Do we have a test for cases where there are spaces in the name itself, similar to `"aws::owners": "self, my     owner, 123456789"`

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

**Review by engedaam — COMMENTED** [review]
/karpenter snapshot
