### PR TITLE
fix: consider pod density in memory overhead calc

### LINKED ISSUE #1959: Calculated available memory does not fit
## Version

**Karpenter**: v0.11.1

**Kubernetes**: v1.22.9-eks-a64ea69

## Expected Behavior

Karpenter scales up an EC2 instance that can fit the pod requests into its allocatable memory.

## Actual Behavior

Karpenter spins up an EC2 instance without enough allocatable memory, leading the pod to be in Pending state forever. This will also cause some node churn, as Karpenter keeps spinning up new nodes when the in-flight capacity does not work out. This seems to happen when the memory requests are close to a certain edge, such as in the example deployment below. In our case this led to Karpenter provisioning a c5n.xlarge instance over and over, with the affected pod never coming up.

The allocatable memory of the node after it is spun up is reported as `8739468Ki` (`8949215232` bytes), while Karpenter is scheduling for a workload of `9037933121` bytes.

We think this might be an issue related to how Karpenter calculates the allocatable memory when scheduling without ENI based pod density (i.e. 110 max pods for all instance types), as it looks like the overhead is always calculated based on the ENI numbers currently.

## Steps to Reproduce the Problem

1. Run Karpenter with `AWS_ENI_LIMITED_POD_DENSITY` set to `false`.
2. Configure the provisoner as shown below.
3. Create the deployment.
4. Observe Karpenter trying to spin up c5n.xlarge. (The mismatch between calculated and real allocatable memory should be present on all node types though.)

## Resource Specs and Logs

Note that I included our full provisioner spec - it may not be reproducible as is on a fresh cluster as we use IPv6 and Cilium.

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: default
spec:
  kubeletConfiguration:
    clusterDNS:
      - fdac:2175:8016::a
  limits:
    resources:
      cpu: 1k
  provider:
    amiFamily: Bottlerocket
    blockDeviceMappings:
      - deviceName: /dev/xvda
        ebs:
          deleteOnTermination: true
          encrypted: true
          volumeSize: 2G
          volumeType: gp3
      - deviceName: /dev/xvdb
        ebs:
          deleteOnTermination: true
          encrypted: true
          volumeSize: 25G
          volumeType: gp3
    securityGroupSelector:
      karpenter.sh/discovery: terratest-u1q5gG
    subnetSelector:
      karpenter.sh/discovery: terratest-u1q5gG
      kubernetes.io/role/internal-elb: '1'
    tags:
      karpenter.sh/discovery: terratest-u1q5gG
  requirements:
    - key: karpenter.sh/capacity-type
      operator: In
      values:
        - spot
        - on-demand
    - key: kubernetes.io/arch
      operator: In
      values:
        - amd64
        - arm64
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
        - a1.2xlarge
        - a1.4xlarge
        - a1.xlarge
        - c5.12xlarge
        - c5.18xlarge
        - c5.24xlarge
        - c5.2xlarge
        - c5.4xlarge
        - c5.9xlarge
        - c5.xlarge
        - c5a.12xlarge
        - c5a.16xlarge
        - c5a.24xlarge
        - c5a.2xlarge
        - c5a.4xlarge
        - c5a.8xlarge
        - c5a.xlarge
        - c5ad.12xlarge
        - c5ad.16xlarge
        - c5ad.24xlarge
        - c5ad.2xlarge
        - c5ad.4xlarge
        - c5ad.8xlarge
        - c5ad.xlarge
        - c5d.12xlarge
        - c5d.18xlarge
        - c5d.24xlarge
        - c5d.2xlarge
        - c5d.4xlarge
        - c5d.9xlarge
        - c5d.xlarge
        - c5n.18xlarge
        - c5n.2xlarge
        - c5n.4xlarge
        - c5n.9xlarge
        - c5n.xlarge
        - c6a.12xlarge
        - c6a.16xlarge
        - c6a.24xlarge
        - c6a.2xlarge
        - c6a.32xlarge
        - c6a.4xlarge
        - c6a.8xlarge
        - c6a.xlarge
        - c6g.12xlarge
        - c6g.16xlarge
        - c6g.2xlarge
        - c6g.4xlarge
        - c6g.8xlarge
        - c6g.xlarge
        - c6gd.12xlarge
        - c6gd.16xlarge
        - c6gd.2xlarge
        - c6gd.4xlarge
        - c6gd.8xlarge
        - c6gd.xlarge
        - c6gn.12xlarge
        - c6gn.16xlarge
        - c6gn.2xlarge
        - c6gn.4xlarge
        - c6gn.8xlarge
        - c6gn.xlarge
        - c6i.12xlarge
        - c6i.16xlarge
        - c6i.24xlarge
        - c6i.2xlarge
        - c6i.32xlarge
        - c6i.4xlarge
        - c6i.8xlarge
        - c6i.xlarge
        - d3.2xlarge
        - d3.4xlarge
        - d3.8xlarge
        - d3.xlarge
        - g4ad.16xlarge
        - g4ad.2xlarge
        - g4ad.4xlarge
        - g4ad.8xlarge
        - g4ad.xlarge
        - g4dn.12xlarge
        - g4dn.16xlarge
        - g4dn.2xlarge
        - g4dn.4xlarge
        - g4dn.8xlarge
        - g4dn.xlarge
        - i3en.12xlarge
        - i3en.24xlarge
        - i3en.2xlarge
        - i3en.3xlarge
        - i3en.6xlarge
        - i3en.xlarge
        - inf1.24xlarge
        - inf1.2xlarge
        - inf1.6xlarge
        - inf1.xlarge
        - m5.12xlarge
        - m5.16xlarge
        - m5.24xlarge
        - m5.2xlarge
        - m5.4xlarge
        - m5.8xlarge
        - m5.xlarge
        - m5a.12xlarge
        - m5a.16xlarge
        - m5a.24xlarge
        - m5a.2xlarge
        - m5a.4xlarge
        - m5a.8xlarge
        - m5a.xlarge
        - m5ad.12xlarge
        - m5ad.16xlarge
        - m5ad.24xlarge
        - m5ad.2xlarge
        - m5ad.4xlarge
        - m5ad.8xlarge
        - m5ad.xlarge
        - m5d.12xlarge
        - m5d.16xlarge
        - m5d.24xlarge
        - m5d.2xlarge
        - m5d.4xlarge
        - m5d.8xlarge
        - m5d.xlarge
        - m5dn.12xlarge
        - m5dn.16xlarge
        - m5dn.24xlarge
        - m5dn.2xlarge
        - m5dn.4xlarge
        - m5dn.8xlarge
        - m5dn.xlarge
        - m5n.12xlarge
        - m5n.16xlarge
        - m5n.24xlarge
        - m5n.2xlarge
        - m5n.4xlarge
        - m5n.8xlarge
        - m5n.xlarge
        - m5zn.12xlarge
        - m5zn.2xlarge
        - m5zn.3xlarge
        - m5zn.6xlarge
        - m5zn.xlarge
        - m6a.12xlarge
        - m6a.16xlarge
        - m6a.24xlarge
        - m6a.2xlarge
        - m6a.32xlarge
        - m6a.4xlarge
        - m6a.8xlarge
        - m6a.xlarge
        - m6g.12xlarge
        - m6g.16xlarge
        - m6g.2xlarge
        - m6g.4xlarge
        - m6g.8xlarge
        - m6g.xlarge
        - m6gd.12xlarge
        - m6gd.16xlarge
        - m6gd.2xlarge
        - m6gd.4xlarge
        - m6gd.8xlarge
        - m6gd.xlarge
        - m6i.12xlarge
        - m6i.16xlarge
        - m6i.24xlarge
        - m6i.2xlarge
        - m6i.32xlarge
        - m6i.4xlarge
        - m6i.8xlarge
        - m6i.xlarge
        - p4d.24xlarge
        - r5.12xlarge
        - r5.16xlarge
        - r5.24xlarge
        - r5.2xlarge
        - r5.4xlarge
        - r5.8xlarge
        - r5.xlarge
        - r5a.12xlarge
        - r5a.16xlarge
        - r5a.24xlarge
        - r5a.2xlarge
        - r5a.4xlarge
        - r5a.8xlarge
        - r5a.xlarge
        - r5ad.12xlarge
        - r5ad.16xlarge
        - r5ad.24xlarge
        - r5ad.2xlarge
        - r5ad.4xlarge
        - r5ad.8xlarge
        - r5ad.xlarge
        - r5b.12xlarge
        - r5b.16xlarge
        - r5b.24xlarge
        - r5b.2xlarge
        - r5b.4xlarge
        - r5b.8xlarge
        - r5b.xlarge
        - r5d.12xlarge
        - r5d.16xlarge
        - r5d.24xlarge
        - r5d.2xlarge
        - r5d.4xlarge
        - r5d.8xlarge
        - r5d.xlarge
        - r5dn.12xlarge
        - r5dn.16xlarge
        - r5dn.24xlarge
        - r5dn.2xlarge
        - r5dn.4xlarge
        - r5dn.8xlarge
        - r5dn.xlarge
        - r5n.12xlarge
        - r5n.16xlarge
        - r5n.24xlarge
        - r5n.2xlarge
        - r5n.4xlarge
        - r5n.8xlarge
        - r5n.xlarge
        - r6g.12xlarge
        - r6g.16xlarge
        - r6g.2xlarge
        - r6g.4xlarge
        - r6g.8xlarge
        - r6g.xlarge
        - r6gd.12xlarge
        - r6gd.16xlarge
        - r6gd.2xlarge
        - r6gd.4xlarge
        - r6gd.8xlarge
        - r6gd.xlarge
        - t3.2xlarge
        - t3.xlarge
        - t3a.2xlarge
        - t3a.xlarge
        - t4g.2xlarge
        - t4g.xlarge
        - x2idn.16xlarge
        - x2idn.24xlarge
        - x2idn.32xlarge
        - x2iedn.16xlarge
        - x2iedn.24xlarge
        - x2iedn.2xlarge
        - x2iedn.32xlarge
        - x2iedn.4xlarge
        - x2iedn.8xlarge
        - x2iedn.xlarge
        - z1d.12xlarge
        - z1d.2xlarge
        - z1d.3xlarge
        - z1d.6xlarge
        - z1d.xlarge
  startupTaints:
    - effect: NoExecute
      key: node.cilium.io/agent-not-ready
      value: 'true'
  ttlSecondsAfterEmpty: 60
  ttlSecondsUntilExpired: 604800
```

The `nodeSelector` here helps make it reproducible, the same issue can happen without it depending on availability of instance types.

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
  namespace: inflate
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      nodeSelector:
        node.kubernetes.io/instance-type: c5n.xlarge
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          securityContext:
            runAsNonRoot: true
            runAsUser: 1000
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
          resources:
            requests:
              cpu: 224m
              memory: 8791517761
            limits:
              cpu: 1120m
              memory: 17403035522
```

```console
2022-06-21T06:39:33.966Z	INFO	controller.provisioning	Computed 1 new node(s) will fit 1 pod(s)	{"commit": "eb05b1e"}
2022-06-21T06:39:33.966Z	INFO	controller.provisioning	Computed 1 unready node(s) will fit 1 pod(s)	{"commit": "eb05b1e"}
2022-06-21T06:39:35.864Z	INFO	controller.provisioning.cloudprovider	Launched instance: i-0964f0c8513910555, hostname: ip-172-16-61-152.eu-central-1.compute.internal, type: c5n.xlarge, zone: eu-central-1a, capacityType: spot	{"commit": "eb05b1e", "provisioner": "default"}
2022-06-21T06:39:35.890Z	INFO	controller.provisioning	Created node with 1 pods requesting {"cpu":"559m","memory":"9037933121","pods":"8"} from types c5n.xlarge	{"commit": "eb05b1e", "provisioner": "default"}
2022-06-21T06:39:35.890Z	INFO	controller.provisioning	Waiting for unschedulable pods	{"commit": "eb05b1e"}
```

### PR DESCRIPTION
**Pull request by mKeRix**
Fixes #1959

**Description**
This change will take the pod density setting in account when calculating memory overhead. This is important to avoid scheduling mistakes and endless loops like described in the linked issue.

**How was this change tested?**

* Real EKS cluster using the manifests from the issue
* Newly added automated tests

See new logs when testing against the reproducible setup (as expected, the c5n.xlarge instance type is now considered to be too small):

```console
2022-06-21T07:09:04.372Z	DEBUG	controller.provisioning	Relaxing soft constraints for pod since it previously failed to schedule, removing: spec.topologySpreadConstraints = {"maxSkew":1,"topologyKey":"topology.kubernetes.io/zone","whenUnsatisfiable":"ScheduleAnyway","labelSelector":{"matchLabels":{"app":"inflate"}}}	{"commit": "153d333"}
2022-06-21T07:09:04.376Z	DEBUG	controller.provisioning	Relaxing soft constraints for pod since it previously failed to schedule, adding: toleration for PreferNoSchedule taints	{"commit": "153d333"}
2022-06-21T07:09:04.379Z	ERROR	controller.provisioning	Could not schedule pod, incompatible with provisioner "default", no instance type satisfied resources {"cpu":"224m","memory":"8791517761","pods":"1"} and requirements karpenter.sh/capacity-type In [on-demand spot], kubernetes.io/arch In [amd64 arm64], node.kubernetes.io/instance-type In [c5n.xlarge], karpenter.sh/provisioner-name In [default]; incompatible with provisioner "long-running", did not tolerate idealo.de/long-running=true:NoSchedule	{"commit": "153d333", "pod": "inflate/inflate-5bb76d8549-rprbr"}
```

Once you remove the `nodeSelector` it picks a list of instance types correctly:

```console
2022-06-21T07:11:34.973Z	DEBUG	controller.provisioning.cloudprovider	Created launch template, Karpenter-terratest-u1q5gG-10432077704041859839	{"commit": "153d333", "provisioner": "default"}
2022-06-21T07:11:36.890Z	INFO	controller.provisioning.cloudprovider	Launched instance: i-0e752dc6a294469a1, hostname: ip-172-16-66-212.eu-central-1.compute.internal, type: c6i.2xlarge, zone: eu-central-1b, capacityType: spot	{"commit": "153d333", "provisioner": "default"}
2022-06-21T07:11:36.922Z	INFO	controller.provisioning	Created node with 1 pods requesting {"cpu":"559m","memory":"9037933121","pods":"8"} from types m6i.xlarge, m5zn.xlarge, t3a.xlarge, t3.xlarge, m6a.xlarge and 193 other(s)	{"commit": "153d333", "provisioner": "default"}
```

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```release-note
Fixed calculation of allocatable memory when not using ENI-based pod density
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Comment by dewjam** [comment]
Hey @mKeRix ,
Thanks for submitting the PR.  I'm going to pull down your code and do some testing of my own.  In the meantime, can you work on adding some automated tests?

**Review by dewjam — CHANGES_REQUESTED** [review]
Per my previous comment, please add some automated testing.

File: pkg/cloudprovider/aws/instancetype.go [hunk 1]
```diff
@@ -270,7 +269,7 @@ func (i *InstanceType) computeOverhead(vmMemOverhead float64) v1.ResourceList {
 			// vm-overhead
 			(int64(math.Ceil(float64(memory.Value())*vmMemOverhead/1024/1024)))+
 				// kube-reserved
-				((11*i.eniLimitedPods())+255)+
+				((11*pods.Value())+255)+
```
[the remark this answers is not in the document]
Comment (mKeRix) [reply pkg/cloudprovider/aws/instancetype.go:272]: Interesting! Bottlerocket seems to behave differently then, as you can see [here](https://github.com/bottlerocket-os/bottlerocket/blob/5d69ebc1fc76a6032b677c9f3941bfa58221f3af/packages/kubernetes-1.22/kubelet-config#L71) and [here](https://github.com/bottlerocket-os/bottlerocket/blob/862c4fa3b9c09a8f6696c360a63ba644b3caaf35/sources/api/schnauzer/src/helpers.rs#L921). When max-pods is set in the user data it seems to always configure `max_pods*11+255 Mi` for the kube reserved memory. Without it, it will take the ENI based pod limits (or 110 as default if it doesn't have the data, e.g. for new instance types).

While I agree that this is a waste on small instance types, I would argue that Karpenter should calculate in the same ways as the AMIs do. Maybe a future update could consider a more dynamic max pods setting for non ENI based pod density (e.g. scale based on available vCPUs)? The code from this PR should already work out of the box then.

I do wonder what an appropriate way forward would be. Since these values are pre-calculated I don't think I can build a switch statement based on the AMI family here. I can add some code to the AL2 AMI user data generation that will override the reserved memory with the more appropriate one maybe? That would have the additional benefit of working around the issue you mentioned. What do you think?

**Comment by mKeRix** [comment]
@dewjam fyi: I'm happy to look at adding some test code - before investing more time I'd like to wait for some input on the direction of this PR (see other comment) though.

File: pkg/cloudprovider/aws/instancetype.go (hunk 1 above)
[the remark this answers is not in the document]
Comment (suket22) [reply pkg/cloudprovider/aws/instancetype.go:272]: Ah I see - so the reason you're seeing a difference in behavior is because you're using Bottlerocket and kubeReserved is being calculated differently by that AMI (compared to AL2). I see that your difference in allocatable as per #1959 was `84.60 Mebibytes` (`9037933121 - 8949215232` bytes). But if I'm calculating correctly, I'd have expected a larger diff since 893Mb is what we're calculating (11 * 58 + 255) in the binpacking logic,  and the BottleRocket AMI is doing 1465Mb.

I agree that we should match the calculation of the AMI in the bin-packing logic and I'm open to changing the way we bin-pack for Bottlerocket nodes. 

In th elong term, I think we want the maxPods memory calculation to be a function of the memory on the instanceType and use something [like this](https://cloud.google.com/kubernetes-engine/docs/concepts/cluster-architecture#memory_cpu).

[the remark this answers is not in the document]
Comment (mKeRix) [reply pkg/cloudprovider/aws/instancetype.go:272]: I just had another look with a fresh set of eyes and realized that my thoughts from the last comment were way off. I'll implement the calculation adjustment based on AMI family as you suggested and will report back. Thanks for all your input!

**Comment by mKeRix** [comment]
Hey @dewjam & @suket22, I've updated the PR with an implementation that takes the AMIFamily into account when calculating the pod memory overhead and added some tests. I'd appreciate a new review. :)

**Comment by mKeRix** [comment]
I just rebased the branch on the latest changes from main and simplified the tests. Is there anything else I can do to help this get merged?

**Comment by ellistarn** [comment]
Some folks are out for the long weekend @mKeRix . Thanks for your patience and we'll get to this as soon as we can.

**Comment by mKeRix** [comment]
Hey there, just wanted to check in again to see if we can get this moving? We'd love to see this change in an upstream release.

**Comment by ellistarn** [comment]
@suket22 @dewjam

File: pkg/cloudprovider/aws/amifamily/resolver.go [hunk 2]
```diff
@@ -75,6 +75,7 @@ type AMIFamily interface {
 	DefaultMetadataOptions() *v1alpha1.MetadataOptions
 	EphemeralBlockDevice() *string
 	EphemeralBlockDeviceOverhead() resource.Quantity
+	ENILimitedMemoryOverhead() bool
```
Comment (suket22) [inline pkg/cloudprovider/aws/amifamily/resolver.go:78]: I think `MaxPods(i *InstanceType) int` might've been more flexible so if there's further divergence in how different AMIs are calculating MaxPods, we can just modify the AMI specific calculation and leave the others. 

Not blocking on this PR though, we can re-work that later 👍

File: pkg/cloudprovider/aws/suite_test.go [hunk 3]
```diff
@@ -370,6 +370,50 @@ var _ = Describe("Allocation", func() {
...
+			Context("AL2", func() {
+				It("should calculate memory overhead based on eni limited pods when ENI limited", func() {
+					opts.AWSENILimitedPodDensity = true
+					opts.VMMemoryOverhead = 0 // cutting a factor out of the equation
+					provider.AMIFamily = &v1alpha1.AMIFamilyAL2
+					instanceInfo, err := instanceTypeProvider.getInstanceTypes(ctx, provider)
+					Expect(err).To(BeNil())
+					it := NewInstanceType(injection.WithOptions(ctx, opts), instanceInfo["m5.xlarge"], 0, provider, nil)
+					overhead := it.Overhead()
+					Expect(overhead.Memory().String()).To(Equal("3073Mi"))
```
Comment (suket22) [inline pkg/cloudprovider/aws/suite_test.go:382]: I was very confused reading `3073Mi` tbh, because that couldn't be right for an m5.xlarge. 
Did a little debugging, and the problem is in our [mocked EC2 response here](https://github.com/aws/karpenter/blob/main/pkg/cloudprovider/aws/fake/ec2api.go#L375). That should be `15` and not `60` which gives you an actual memory overhead of `1093Mi` instead for an m5.xlarge. 

Would you mind switching that 60 to a 15 and updating this PR?

File: pkg/cloudprovider/aws/suite_test.go [hunk 4]
```diff
@@ -370,6 +370,50 @@ var _ = Describe("Allocation", func() {
...
+				})
+				It("should calculate memory overhead based on max pods when not ENI limited", func() {
+					opts.AWSENILimitedPodDensity = false
+					opts.VMMemoryOverhead = 0 // cutting a factor out of the equation
+					provider.AMIFamily = &v1alpha1.AMIFamilyBottlerocket
+					instanceInfo, err := instanceTypeProvider.getInstanceTypes(ctx, provider)
+					Expect(err).To(BeNil())
+					it := NewInstanceType(injection.WithOptions(ctx, opts), instanceInfo["m5.xlarge"], 0, provider, nil)
+					overhead := it.Overhead()
+					Expect(overhead.Memory().String()).To(Equal("1665Mi"))
```
Comment (suket22) [inline pkg/cloudprovider/aws/suite_test.go:414]: First I was confused how we aren't limited by ENIs yet our overhead for BR dropped from `3073Mi` to `1665Mi`. 
I think it makes sense now since it should rather be an increase from `1093Mi` to `1665Mi`.

**Review by suket22 — COMMENTED** [review]
Apologies for the wait, and thank you for making this change.
Mostly LGTM, just need to flip a couple numbers in the tests :)

File: pkg/cloudprovider/aws/suite_test.go (hunk 3 above)
Comment (mKeRix) [reply pkg/cloudprovider/aws/suite_test.go]: Good catch! I've pushed a commit that updates the mock response and corresponding assertions. I did manually calculate the values to verify during the implementation, but honestly never thought about the logic of the two values. This should make the intention much more clear.

File: pkg/cloudprovider/aws/amifamily/resolver.go (hunk 2 above)
Comment (mKeRix) [reply pkg/cloudprovider/aws/amifamily/resolver.go:78]: For this specific issue something like `MemoryOverhead(i *InstanceType) resource.Quantity` might be better (as the difference is in the calculation of the overhead, the max pods match correctly in the current implementation). Nonetheless, I think both functions would be a great addition and would give more flexibility in the implementation. 👍

**Comment by mKeRix** [comment]
@suket22 I've updated the PR according to your comments - would appreciate another review. :)

**Review by suket22 — APPROVED** [review]

**Comment by dewjam** [comment]
Hey @mKeRix ,
I'm testing your PR now, just to confirm some behaviors.  I should be able to give you an update today.  Thanks for your patience!

**Review by dewjam — APPROVED** [review]
