### PR TITLE
fix: Separate zone caching by subnet selectors

### LINKED ISSUE #2228: [aws] Failure/unpredictability in assigning nodes if provisioners target different subnets
## Version

**Karpenter**: v0.13.2

**Kubernetes**: v1.21.12-eks-a64ea69

## Expected Behavior
If I have:
* N provisioners which have a subnet selector that matches Zones A and B
* and 1 provisioner that matches zone C
* Then a pod that targets the latter provisioner should be able to find a node.

## Actual Behavior
The pod mostly fails to find a node with errors of the form (logs from the karpenter controller):

```
2022-07-31T21:12:35.539Z        ERROR   controller.provisioning Could not schedule pod, incompatible with provisioner "test", no instance type satisfied resources {"memory":"5Gi",pods":"1"} and requirements karpenter.sh/capacity-type In [on-demand], kubernetes.io/arch In [amd64], karpenter.sh/provisioner-name In [test], node.kubernetes.io/instance-type In [t3a.2xlarge]; incompatible with provisioner "default",  ...    {"commit": "062a029", "pod": "default/test-karpenter"}
```

But sometimes randomly succeeds.
The problem gets more pronounced as N increases, i.e., if there are 5 provisioners targeting a different subnet than the one.

## Resource Specs and Logs
Skipping this section since a proposed fix is in #2229

### PR DESCRIPTION
**Pull request by asimshankar**
Fixes #2228

**Description**

The set of zones for instance types was using the same cache key irrespective of the subnet selector. As a result, if two provisioners had distinct subnetSelectors that matched subnets in different availability zones, the karpenter controller would only see one of them and be unable to schedule nodes on some of the subnets.

**How was this change tested?**

Manually tested by patching this change on top of the v0.13.2-release branch in our cluster.

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```release-note
Fix flakiness in setting up nodes in the right availability zone when provisioners target different subnets.
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/cloudprovider/aws/instancetypes.go [hunk 1]
```diff
@@ -136,8 +143,8 @@ func (p *InstanceTypeProvider) getInstanceTypeZones(ctx context.Context, provide
 		}); err != nil {
 		return nil, fmt.Errorf("describing instance type zone offerings, %w", err)
 	}
-	logging.FromContext(ctx).Debugf("Discovered EC2 instance types zonal offerings")
-	p.cache.SetDefault(InstanceTypeZonesCacheKey, instanceTypeZones)
+	logging.FromContext(ctx).Debugf("Discovered EC2 instance types zonal offerings (cache key: %v)", cacheKey)
```
Comment (ellistarn) [inline pkg/cloudprovider/aws/instancetypes.go:146]:
```suggestion
	logging.FromContext(ctx).Debugf("Discovered EC2 instance types zonal offerings for subnets %s, pretty.Concise(provider.SubnetSelector))
```

**Review by ellistarn — COMMENTED** [review]
Nice fix! One minor recommendation

**Comment by asimshankar** [comment]
> Nice fix! One minor recommendation

Thanks for the quick turnaround! Applied the recommendation.

File: pkg/cloudprovider/aws/instancetypes.go [hunk 2]
```diff
@@ -136,8 +143,8 @@ func (p *InstanceTypeProvider) getInstanceTypeZones(ctx context.Context, provide
 		}); err != nil {
 		return nil, fmt.Errorf("describing instance type zone offerings, %w", err)
 	}
-	logging.FromContext(ctx).Debugf("Discovered EC2 instance types zonal offerings")
-	p.cache.SetDefault(InstanceTypeZonesCacheKey, instanceTypeZones)
+	logging.FromContext(ctx).Debugf("Discovered EC2 instance types zonal offerings for subnets %s, pretty.Concise(provider.SubnetSelector))
```
Comment (bwagner5) [inline pkg/cloudprovider/aws/instancetypes.go:146]:
```suggestion
	logging.FromContext(ctx).Debugf("Discovered EC2 instance types zonal offerings for subnets %s", pretty.Concise(provider.SubnetSelector))
```

**Review by bwagner5 — COMMENTED** [review]
lgtm! Just one missing `"`

**Comment by bwagner5** [comment]
looks like `"github.com/aws/karpenter/pkg/utils/pretty"` needs to be imported as well.

**Comment by asimshankar** [comment]
> looks like `"github.com/aws/karpenter/pkg/utils/pretty"` needs to be imported as well.

Sorry for the bumbling around, fixed. Will keep an eye on any new silly compile errors.

**Review by bwagner5 — APPROVED** [review]
lgtm!

**Comment by avinashparchuri** [comment]
@bwagner5 would it be possible to get this into a new RC (or if there is a regular release coming up, that would work as well)? Thanks!

**Comment by bwagner5** [comment]
We have snapshot builds, this includes this PR: public.ecr.aws/karpenter/controller:f4594705f9d20d3d1568fe5f989112dabbc51579
