### PR TITLE
fix: undefined blockdevicemappings volumesize would panic if not defaulted

### LINKED ISSUE #3409: Webhook didn't catch an error in spec.blockDeviceMappings[*].ebs settings
### Version

__Karpenter Version:__ v0.24.0

__Kubernetes Version:__ v1.23.0

### Expected Behavior

If there is an error in the settings of an `AWSNodeTemplate` it should be cached by the karpenter validating webhook.

In my case It seems karpenter is forcing me to define an `ebs.volumeSize` when I already defined an `ebs.snapshotID`.

However, according the [aws API documentation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_EbsBlockDevice.html#:~:text=VolumeSize%20(request)%2C%20volumeSize,than%20the%20snapshot%20size.) is only required one of the two, and is possible to define both under a condition:

> The size of the volume, in GiBs. You must specify either a snapshot ID or a volume size. If you specify a snapshot, the default is the snapshot size. You can specify a volume size that is equal to or larger than the snapshot size.

### Actual Behavior

I was trying to deploy a Provisioner refering to an `AWSNodeTemplate` with missing required fields (I was not aware of) in the `blockDeviceMappings` section , the validating webhook let it pass and be deployed. 
Right away the karpenter pods start to crash letting the karpenter useless.

karpenter pods watch:
```shell
kubectl -n karpenter get po -w
NAME                         READY   STATUS    RESTARTS   AGE
karpenter-6f4fdc54c6-fxbwk   1/1     Running   0          19s
karpenter-6f4fdc54c6-m7ffd   1/1     Running   0          19s
karpenter-6f4fdc54c6-fxbwk   0/1     Error     0          85s
karpenter-6f4fdc54c6-fxbwk   0/1     Running   1 (2s ago)   86s
karpenter-6f4fdc54c6-fxbwk   1/1     Running   1 (4s ago)   88s
karpenter-6f4fdc54c6-m7ffd   0/1     Error     0            106s
karpenter-6f4fdc54c6-m7ffd   0/1     Running   1 (3s ago)   108s
karpenter-6f4fdc54c6-m7ffd   1/1     Running   1 (5s ago)   110s
karpenter-6f4fdc54c6-fxbwk   0/1     Error     1 (40s ago)   2m4s
karpenter-6f4fdc54c6-fxbwk   0/1     CrashLoopBackOff   1 (7s ago)    2m11s
karpenter-6f4fdc54c6-m7ffd   0/1     Error              1 (38s ago)   2m23s
karpenter-6f4fdc54c6-fxbwk   0/1     Running            2 (20s ago)   2m24s
karpenter-6f4fdc54c6-fxbwk   1/1     Running            2 (23s ago)   2m27s
karpenter-6f4fdc54c6-m7ffd   0/1     CrashLoopBackOff   1 (9s ago)    2m31s
karpenter-6f4fdc54c6-m7ffd   0/1     Running            2 (23s ago)   2m45s
karpenter-6f4fdc54c6-fxbwk   0/1     Error              2 (41s ago)   2m45s
karpenter-6f4fdc54c6-m7ffd   1/1     Running            2 (25s ago)   2m47s
karpenter-6f4fdc54c6-fxbwk   0/1     CrashLoopBackOff   2 (7s ago)    2m51s
karpenter-6f4fdc54c6-m7ffd   0/1     Error              2 (45s ago)   3m7s
```

### Steps to Reproduce the Problem

Define a provisioner that refers to an AWSNodeTemplate as follows:

```yaml
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: my-provisioner
spec:
  providerRef:
    name: my-node-template
...
```

Define an AWSNodeTemplate that will use a snapshot as follows:

```yaml
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: my-node-template
spec:
  blockDeviceMappings:
    - deviceName: /dev/xvdb
      ebs:
        deleteOnTermination: true
        snapshotID: snap-0a2000008824631
...
```

I am going to focus in the blockDeviceMappings section that was my case, but might be happening in other nested sections under `spec`

Deploy both resources:

```shell
kubectl apply -f <provisioner-and-node-template.yaml>
```

No complains shown by the karpenter webhook.

Watch the karpenter pods:

```shell
kubectl -n karpenter get po -w
```

Karpenter pods shoud start to restart and eventually crash both

You will not be able to do any other operation like editing karpenter resources (the node template)  or delete it because the karpenter webhook won't be available. 

```shell
kubectl delete provisioners.karpenter.sh my-provisioner
Error from server (InternalError): Internal error occurred: failed calling webhook "validation.webhook.karpenter.sh": failed to call webhook: Post "https://karpenter.karpenter.svc:443/validate/karpenter.sh?timeout=10s": no endpoints available for service "karpenter"
```

```shell
kubectl delete awsnodetemplates.karpenter.k8s.aws my-node-template
Error from server (InternalError): Internal error occurred: failed calling webhook "validation.webhook.karpenter.k8s.aws": failed to call webhook: Post "https://karpenter.karpenter.svc:443/validate/karpenter.k8s.aws?timeout=10s": no endpoints available for service "karpenter"
```

To solve it you need to rollout restart the karpenter deployment and patch the faulty AWSNodeTemplate right away, previous they start to crash again.

### Resource Specs and Logs

Logs were not useful to find the issue:
```shell
2023-02-16T19:04:04.066Z	INFO	controller	Starting workers	{"commit": "8c27519-dirty", "controller": "node", "controllerGroup": "", "controllerKind": "Node", "worker count": 10}
2023-02-16T19:04:04.077Z	INFO	controller	Starting workers	{"commit": "8c27519-dirty", "controller": "inflightchecks", "controllerGroup": "", "controllerKind": "Node", "worker count": 10}
2023-02-16T19:04:04.077Z	INFO	controller	Starting workers	{"commit": "8c27519-dirty", "controller": "counter", "controllerGroup": "karpenter.sh", "controllerKind": "Provisioner", "worker count": 10}
2023-02-16T19:04:04.128Z	DEBUG	controller.awsnodetemplate	discovered security groups	{"commit": "8c27519-dirty", "awsnodetemplate": "bottlerocket", "security-groups": ["sg-0830faredacted366"]}
2023-02-16T19:04:04.953Z	DEBUG	controller.deprovisioning	discovered EC2 instance types	{"commit": "8c27519-dirty", "instance-type-count": 505}
2023-02-16T19:04:05.092Z	DEBUG	controller.deprovisioning	discovered EC2 instance types zonal offerings for subnets	{"commit": "8c27519-dirty", "subnet-selector": "{\"Name\":\"*Private*\",\"karpenter.sh/discovery\":\"my-cluster\"}"}
2023-02-16T19:04:05.118Z	INFO	controller.deprovisioning	stopping controller	{"commit": "8c27519-dirty"}
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x1c521fb]

goroutine 750 [running]:
github.com/aws/karpenter/pkg/cloudprovider.computeCapacity({0x2ce89d8, 0xc001dd2c90}, 0xc000ce4c00, {0x2cec768, 0xc0020b0b50}, {0xc0020b0b48, 0x1, 0x1}, 0xc000056023?)
	github.com/aws/karpenter/pkg/cloudprovider/instancetype.go:134 +0x1db
github.com/aws/karpenter/pkg/cloudprovider.NewInstanceType({0x2ce89d8, 0xc001dd2c90}, 0xc000ce4c00, 0x0?, {0xc000056023, 0xc}, 0xc0016183c0, {0xc00340af00, 0x6, 0x8})
	github.com/aws/karpenter/pkg/cloudprovider/instancetype.go:58 +0x315
github.com/aws/karpenter/pkg/cloudprovider.(*InstanceTypeProvider).List(0xc000c2fc20, {0x2ce89d8, 0xc001dd2c90}, 0x0?, 0xc0016183c0)
	github.com/aws/karpenter/pkg/cloudprovider/instancetypes.go:112 +0x425
github.com/aws/karpenter/pkg/cloudprovider.(*CloudProvider).GetInstanceTypes(0xc000d6f3b0, {0x2ce89d8, 0xc001dd2c90}, 0xc0010a09c8)
	github.com/aws/karpenter/pkg/cloudprovider/cloudprovider.go:181 +0x9a
github.com/aws/karpenter-core/pkg/cloudprovider/metrics.(*decorator).GetInstanceTypes(0xc000d38190, {0x2ce89d8, 0xc001dd2c90}, 0x13?)
	github.com/aws/karpenter-core@v0.23.1-0.20230207002141-6abab235df9c/pkg/cloudprovider/metrics/cloudprovider.go:86 +0x199
github.com/aws/karpenter-core/pkg/controllers/deprovisioning.buildProvisionerMap({0x2ce89d8, 0xc001dd2c90}, {0x2cf3fe8, 0xc000d7ef00}, {0x2cec648, 0xc000d38190})
	github.com/aws/karpenter-core@v0.23.1-0.20230207002141-6abab235df9c/pkg/controllers/deprovisioning/helpers.go:252 +0x1fe
github.com/aws/karpenter-core/pkg/controllers/deprovisioning.candidateNodes({0x2ce89d8, 0xc001dd2c90}, 0xc001dd2cc0?, {0x2cf3fe8, 0xc000d7ef00}, {0x2cede30, 0x419c5d0}, {0x2cec648?, 0xc000d38190?}, 0xc0023f1d50)
	github.com/aws/karpenter-core@v0.23.1-0.20230207002141-6abab235df9c/pkg/controllers/deprovisioning/helpers.go:162 +0x7c
github.com/aws/karpenter-core/pkg/controllers/deprovisioning.(*Controller).Reconcile(0xc00042e0e0, {0x2ce89d8, 0xc001dd2c90}, {{{0x0?, 0x0?}, {0x404d6c?, 0x0?}}})
	github.com/aws/karpenter-core@v0.23.1-0.20230207002141-6abab235df9c/pkg/controllers/deprovisioning/controller.go:110 +0x179
github.com/aws/karpenter-core/pkg/operator/controller.(*Singleton).reconcile(0xc000d6f950, {0x2ce89d8, 0xc001dd2c90})
	github.com/aws/karpenter-core@v0.23.1-0.20230207002141-6abab235df9c/pkg/operator/controller/singleton.go:108 +0xb9
github.com/aws/karpenter-core/pkg/operator/controller.(*Singleton).Start(0xc000d6f950, {0x2ce8930, 0xc000127340})
	github.com/aws/karpenter-core@v0.23.1-0.20230207002141-6abab235df9c/pkg/operator/controller/singleton.go:99 +0x205
sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile.func1(0xc000d28860)
	sigs.k8s.io/controller-runtime@v0.13.0/pkg/manager/runnable_group.go:219 +0xdb
created by sigs.k8s.io/controller-runtime/pkg/manager.(*runnableGroup).reconcile
	sigs.k8s.io/controller-runtime@v0.13.0/pkg/manager/runnable_group.go:203 +0x1ad
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by njtran**
Fixes #3409

**Description**
Our ephemeral storage calculation would assume a volume size is defined in the AWSNodeTemplate if it had a particular combination of `amiFamily` and `deviceName` set. 

This would panic with an AWSNodeTemplate with values
- For `amiFamily: AL2` and `blockDeviceMappings[0].deviceName=/dev/xvda`
- For `amiFamily: Bottlerocket` and `blockDeviceMappings[0].deviceName=/dev/xvdb`
- For `amiFamily: Ubuntu` and `blockDeviceMappings[0].deviceName=/dev/sda1`
- For `amiFamily: Custom`

**How was this change tested?**

* `make presubmit`
* `make apply` && try to create an AWSNodeTemplate with the first three combinations. 
* then make an AWSNodeTemplate with Custom AMI Family and no volumeSize. 

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [x] No

**Release Note**

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/apis/v1alpha1/suite_test.go [hunk 1]
```diff
@@ -105,4 +109,100 @@ var _ = Describe("Validation", func() {
...
+					DeviceName: v1alpha1.EphemeralBlockDevice(v1alpha1.AMIFamilyAL2),
+					EBS: &v1alpha1.BlockDevice{
+						SnapshotID: aws.String("snap-xxxxxxxx"),
+						VolumeType: aws.String(ec2.VolumeTypeGp3),
+					},
+				},
+			}
+			Expect(ant.Validate(ctx)).To(Succeed())
+		})
+		It("should fail when both volumeSize and snapshotID are set", func() {
```
Comment (bwagner5) [inline pkg/apis/v1alpha1/suite_test.go:170]: I thought this was allowed as long as the volume size was >= to the snapshot size?

File: pkg/apis/v1alpha1/suite_test.go [hunk 2]
```diff
@@ -105,4 +109,100 @@ var _ = Describe("Validation", func() {
...
+				{
+					DeviceName: v1alpha1.EphemeralBlockDevice(v1alpha1.AMIFamilyCustom),
+					EBS: &v1alpha1.BlockDevice{
+						VolumeType: aws.String(ec2.VolumeTypeGp3),
+					},
+				},
+			}
+			Expect(ant.Validate(ctx)).To(Not(Succeed()))
+		})
+		It("should fail when neither volumeSize is less than the default for gp3", func() {
```
Comment (bwagner5) [inline pkg/apis/v1alpha1/suite_test.go:194]: I don't think this makes sense. GP3 min volume size is 1Gi. Was this supposed to test that volume size is >= snapshot size?  

The test name is also confusing here :)

File: pkg/providers/instancetype/types.go [hunk 3]
```diff
@@ -173,12 +173,16 @@ func ephemeralStorage(amiFamily amifamily.AMIFamily, blockDeviceMappings []*v1al
 	if len(blockDeviceMappings) != 0 {
 		switch amiFamily.(type) {
 		case *amifamily.Custom:
-			return blockDeviceMappings[len(blockDeviceMappings)-1].EBS.VolumeSize
+			// We can't know if a custom AMI is going to have a volume size.
```
Comment (bwagner5) [inline pkg/providers/instancetype/types.go:176]: can you add a test for the case this fixes?

File: pkg/providers/instancetype/types.go [hunk 4]
```diff
@@ -173,12 +173,16 @@ func ephemeralStorage(amiFamily amifamily.AMIFamily, blockDeviceMappings []*v1al
...
+			volumeSize := blockDeviceMappings[len(blockDeviceMappings)-1].EBS.VolumeSize
+			if volumeSize != nil {
```
Comment (bwagner5) [inline pkg/providers/instancetype/types.go:178]: This seems reasonable to fallback to the default for the amiFamily. It might be better to look-up the ami default block device mapping so that this is hardcoded as well. We could look into that in a later PR. As a user that specified a customAMI and no volume-size, I'd expect it to use the default block device mapping of the AMI rather than our hardcoded default.

Comment (njtran) [reply pkg/providers/instancetype/types.go:178]: Synced offline, going to discover snapshot size in another PR, will open an issue for this

File: pkg/providers/instancetype/types.go [hunk 5]
```diff
@@ -173,12 +173,16 @@ func ephemeralStorage(amiFamily amifamily.AMIFamily, blockDeviceMappings []*v1al
...
+				return volumeSize
+			}
 		default:
 			ephemeralBlockDevice := amiFamily.EphemeralBlockDevice()
 			for _, blockDevice := range blockDeviceMappings {
-				// If a block device mapping exists in the provider for the root volume, set the volume size specified in the provider
-				if *blockDevice.DeviceName == *ephemeralBlockDevice {
+				// If a block device mapping exists in the provider for the root volume, use the volume size specified in the provider. If not, use the default
```
Comment (jonathan-innis) [inline pkg/providers/instancetype/types.go:184]: optional: Could we simplify this by doing a `lo.Find()` and then returning either the volumeSize or the default?

File: pkg/providers/instancetype/types.go (hunk 4 above)
Comment (jonathan-innis) [inline pkg/providers/instancetype/types.go:178]: optional: Use a `lo.Ternary` with a return statement to shorten this

File: pkg/providers/instancetype/suite_test.go [hunk 6]
```diff
@@ -1331,6 +1331,80 @@ var _ = Describe("Instance Types", func() {
...
+			nodeTemplate.Spec.BlockDeviceMappings = []*v1alpha1.BlockDeviceMapping{
+				{
+					DeviceName: aws.String("/dev/xvda"),
+					EBS: &v1alpha1.BlockDevice{
+						SnapshotID: aws.String("snap-xxxxxxxx"),
+					},
+				},
+			}
+		})
+		It("should default to EBS defaults when volumeSize is not defined in blockDeviceMappings for custom AMIs", func() {
```
Comment (jonathan-innis) [inline pkg/providers/instancetype/suite_test.go:1346]: optional: Consider using a `DescribeTable` here. There's an example of this style [here](https://github.com/aws/karpenter/blob/2765c329d56451461443e43b04ad7740fb01d30d/test/suites/integration/kubelet_config_test.go#L37)

**Review by jonathan-innis — DISMISSED** [review]

File: pkg/providers/instancetype/types.go [hunk 7]
```diff
@@ -173,14 +173,16 @@ func ephemeralStorage(amiFamily amifamily.AMIFamily, blockDeviceMappings []*v1al
...
 		default:
 			ephemeralBlockDevice := amiFamily.EphemeralBlockDevice()
-			for _, blockDevice := range blockDeviceMappings {
-				// If a block device mapping exists in the provider for the root volume, set the volume size specified in the provider
-				if *blockDevice.DeviceName == *ephemeralBlockDevice {
-					return blockDevice.EBS.VolumeSize
-				}
+			// If a block device mapping exists in the provider for the root volume, use the volume size specified in the provider. If not, use the default
+			if blockDeviceMapping, ok := lo.Find(blockDeviceMappings, func(bdm *v1alpha1.BlockDeviceMapping) bool {
+				return *bdm.DeviceName == *ephemeralBlockDevice && bdm.EBS.VolumeSize != nil
```
Comment (jonathan-innis) [inline pkg/providers/instancetype/types.go:183]: optional: I was thinking you could just search for the `blockDeviceMapping` and with a `lo.Find` and then use the response to see if the volumeSize is defined. Either way you do it is fine, I was just thinking one made the code a bit easier to follow

**Review by jonathan-innis — DISMISSED** [review]

File: pkg/providers/instancetype/suite_test.go (hunk 6 above)
Comment (njtran) [reply pkg/providers/instancetype/suite_test.go:1346]: I like the style, but I don't think it helps much since I also have to change the expected device names and ami family strings in the node template. I'm gonna opt to just keep as is

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀

File: pkg/providers/instancetype/types.go (hunk 4 above)
Comment (njtran) [reply pkg/providers/instancetype/types.go]: https://github.com/aws/karpenter/issues/3934
