### PR TITLE
Don't provision for pods with nominated node

### LINKED ISSUE #1050: Pod preemption cause Karpenter to over provision and leave Pods Pending
## Version

**Karpenter**: v0.5.3

**Kubernetes**: v1.23.0

## Expected Behavior
Ideally Karpenter would realis we the preemption event.
At least all Pods being responded to and not left in Pending state for an extended period of time (many minutes)
Launching an instance that will always end up being empty should also be avoided.

## Actual Behavior

When there is a pod preemption there is a race between KCM and kube-scheduler on responding to the new Pods. KCM/kube-scheduler tends to win. So the higher priority Pod is already scheduled when Karpenter has created a new instance and tries to bind the Pod to the new instance. This ends up in an empty Node.
Often, Karpenter fails to react to the evicted Pod, which is then stuck Pending. That is what happens in both cases below.
At other times, Karpenter reacts to it, and because of #1044 it spins up yet another instance.

In both occasions, Karpenter eventually realises there are empty nodes in the cluster and starts terminating instances.

Also note the first log line, where it responds to the low-pri pod being evicted, leaving the node empty for a moment.

I've seen Karpenter trying to batch between 2 (first log) and 6 pods (second log). With 6 Pods, it is taking into account the 3 new Pods + the 3 evicted Pods.

## Steps to Reproduce the Problem
* Create a cluster with 1 Provisioner. I chose to only allow t3.mediums to make this more reproducible. 
* Deploy cluster-overprovisioner (default should be 3 Pods with 1 CPU)
* Deploy a deployment of 3 pods with 1 CPU req
* Watch what happens

## Resource Specs and Logs

```
2021-12-28T16:15:52.904Z        INFO    controller.node Added TTL to empty node {"commit": "5047f3c", "node": "i-043ba5937cb4e30c8"}
2021-12-28T16:15:53.146Z        INFO    controller.provisioning Batched 2 pods in 1.013243904s  {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T16:15:53.167Z        INFO    controller.provisioning Computed packing of 2 node(s) for 2 pod(s) with instance type option(s) [t3.medium]     {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T16:15:53.873Z        INFO    controller.node Removed emptiness TTL from node {"commit": "5047f3c", "node": "i-043ba5937cb4e30c8"}
2021-12-28T16:15:55.327Z        INFO    controller.provisioning Launched instance: i-045ac8998bb06a84e, hostname: i-045ac8998bb06a84e.eu-central-1.compute.internal, type: t3.medium, zone: eu-central-1a, capacityType: spot   {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T16:15:55.328Z        INFO    controller.provisioning Launched instance: i-0c8a97c5fb1c5b12b, hostname: i-0c8a97c5fb1c5b12b.eu-central-1.compute.internal, type: t3.medium, zone: eu-central-1a, capacityType: spot   {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T16:15:55.343Z        INFO    controller.provisioning Bound 1 pod(s) to node i-045ac8998bb06a84e      {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T16:15:55.366Z        ERROR   controller.provisioning Failed to bind default/nginx-deployment-5d475869cd-fnfsj to i-0c8a97c5fb1c5b12b, Operation cannot be fulfilled on pods "nginx-deployment-5d475869cd-fnfsj": StorageError: invalid object, Code: 4, Key: /registry/pods/default/nginx-deployment-5d475869cd-fnfsj, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: ResourceVersion in precondition: 186789, ResourceVersion in object meta: 186820     {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T16:15:55.366Z        INFO    controller.provisioning Bound 0 pod(s) to node i-0c8a97c5fb1c5b12b      {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T16:15:55.367Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "5047f3c", "provisioner": "nodes"}
```

```
2021-12-28T17:00:21.097Z        INFO    controller.node Added TTL to empty node {"commit": "5047f3c", "node": "i-053c76d21c933c2f2"}
2021-12-28T17:00:21.122Z        INFO    controller.provisioning Batched 6 pods in 1.154086803s  {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:21.128Z        INFO    controller.provisioning Computed packing of 3 node(s) for 3 pod(s) with instance type option(s) [t3.medium]     {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:21.607Z        INFO    controller.node Removed emptiness TTL from node {"commit": "5047f3c", "node": "i-053c76d21c933c2f2"}
2021-12-28T17:00:23.357Z        INFO    controller.provisioning Launched instance: i-0fa1d000f7e8d70fc, hostname: i-0fa1d000f7e8d70fc.eu-central-1.compute.internal, type: t3.medium, zone: eu-central-1a, capacityType: spot   {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:23.357Z        INFO    controller.provisioning Launched instance: i-03a0f23f7249bd7ea, hostname: i-03a0f23f7249bd7ea.eu-central-1.compute.internal, type: t3.medium, zone: eu-central-1a, capacityType: spot   {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:23.357Z        INFO    controller.provisioning Launched instance: i-013001444efe77f2f, hostname: i-013001444efe77f2f.eu-central-1.compute.internal, type: t3.medium, zone: eu-central-1a, capacityType: spot   {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:23.369Z        INFO    controller.provisioning Bound 1 pod(s) to node i-0fa1d000f7e8d70fc      {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:23.384Z        INFO    controller.provisioning Bound 1 pod(s) to node i-03a0f23f7249bd7ea      {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:23.405Z        INFO    controller.provisioning Bound 1 pod(s) to node i-013001444efe77f2f      {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:23.426Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [t3.medium]     {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:25.428Z        INFO    controller.provisioning Launched instance: i-0c3852de37033d0b0, hostname: i-0c3852de37033d0b0.eu-central-1.compute.internal, type: t3.medium, zone: eu-central-1c, capacityType: spot   {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:25.444Z        ERROR   controller.provisioning Failed to bind default/nginx-deployment-567bcc57f7-jjwkk to i-0c3852de37033d0b0, Operation cannot be fulfilled on pods "nginx-deployment-567bcc57f7-jjwkk": StorageError: invalid object, Code: 4, Key: /registry/pods/default/nginx-deployment-567bcc57f7-jjwkk, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: ResourceVersion in precondition: 206892, ResourceVersion in object meta: 206942     {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:25.444Z        INFO    controller.provisioning Bound 0 pod(s) to node i-0c3852de37033d0b0      {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:25.457Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [t3.medium]     {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:27.448Z        INFO    controller.provisioning Launched instance: i-0145f43f70f17090d, hostname: i-0145f43f70f17090d.eu-central-1.compute.internal, type: t3.medium, zone: eu-central-1b, capacityType: spot   {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:27.459Z        ERROR   controller.provisioning Failed to bind default/nginx-deployment-567bcc57f7-4g7bb to i-0145f43f70f17090d, Operation cannot be fulfilled on pods "nginx-deployment-567bcc57f7-4g7bb": StorageError: invalid object, Code: 4, Key: /registry/pods/default/nginx-deployment-567bcc57f7-4g7bb, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: ResourceVersion in precondition: 206899, ResourceVersion in object meta: 206945     {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:27.460Z        INFO    controller.provisioning Bound 0 pod(s) to node i-0145f43f70f17090d      {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:27.470Z        INFO    controller.provisioning Computed packing of 1 node(s) for 1 pod(s) with instance type option(s) [t3.medium]     {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:29.515Z        INFO    controller.provisioning Launched instance: i-08d19680923ab04c9, hostname: i-08d19680923ab04c9.eu-central-1.compute.internal, type: t3.medium, zone: eu-central-1a, capacityType: spot   {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:29.537Z        ERROR   controller.provisioning Failed to bind default/nginx-deployment-567bcc57f7-dn2n7 to i-08d19680923ab04c9, Operation cannot be fulfilled on pods "nginx-deployment-567bcc57f7-dn2n7": StorageError: invalid object, Code: 4, Key: /registry/pods/default/nginx-deployment-567bcc57f7-dn2n7, ResourceVersion: 0, AdditionalErrorMsg: Precondition failed: ResourceVersion in precondition: 206903, ResourceVersion in object meta: 206948     {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:29.537Z        INFO    controller.provisioning Bound 0 pod(s) to node i-08d19680923ab04c9      {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:00:29.539Z        INFO    controller.provisioning Waiting for unschedulable pods  {"commit": "5047f3c", "provisioner": "nodes"}
2021-12-28T17:02:44.378Z        INFO    controller.node Added TTL to empty node {"commit": "5047f3c", "node": "i-0c3852de37033d0b0"}
2021-12-28T17:02:55.550Z        INFO    controller.node Added TTL to empty node {"commit": "5047f3c", "node": "i-08d19680923ab04c9"}
2021-12-28T17:02:56.871Z        INFO    controller.node Added TTL to empty node {"commit": "5047f3c", "node": "i-0145f43f70f17090d"}
2021-12-28T17:03:14.407Z        INFO    controller.node Triggering termination after 30s for empty node {"commit": "5047f3c", "node": "i-0c3852de37033d0b0"}
2021-12-28T17:03:14.434Z        INFO    controller.termination  Cordoned node   {"commit": "5047f3c", "node": "i-0c3852de37033d0b0"}
2021-12-28T17:03:14.592Z        INFO    controller.termination  Deleted node    {"commit": "5047f3c", "node": "i-0c3852de37033d0b0"}
2021-12-28T17:03:25.565Z        INFO    controller.node Triggering termination after 30s for empty node {"commit": "5047f3c", "node": "i-08d19680923ab04c9"}
2021-12-28T17:03:25.581Z        INFO    controller.termination  Cordoned node   {"commit": "5047f3c", "node": "i-08d19680923ab04c9"}
2021-12-28T17:03:25.745Z        INFO    controller.termination  Deleted node    {"commit": "5047f3c", "node": "i-08d19680923ab04c9"}
2021-12-28T17:03:26.155Z        INFO    controller.node Triggering termination after 30s for empty node {"commit": "5047f3c", "node": "i-0145f43f70f17090d"}
2021-12-28T17:03:26.170Z        INFO    controller.termination  Cordoned node   {"commit": "5047f3c", "node": "i-0145f43f70f17090d"}
2021-12-28T17:03:28.998Z        INFO    controller.termination  Deleted node    {"commit": "5047f3c", "node": "i-0145f43f70f17090d"}

```

### PR DESCRIPTION
**Pull request by olemarkus**
**1. Issue, if available:**
Fixes #1050 

**2. Description of changes:**
When a pod can evict other pods due to preemption, scheduler sets `pod.Status.NominatedNodeName` to track that scheduler has considered the pod suitable for the given node. As such, Karpenter does not need to take action on the particular node and can instead focus on the evicted pods.

**3. Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: *link to issue*
- [X] No

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/controllers/selection/controller.go [hunk 1]
```diff
@@ -104,7 +104,12 @@ func (c *Controller) selectProvisioner(ctx context.Context, pod *v1.Pod) (errs e
 }
 
 func isProvisionable(p *v1.Pod) bool {
-	return p.Spec.NodeName == "" && pod.FailedToSchedule(p) && !pod.IsOwnedByDaemonSet(p) && !pod.IsOwnedByNode(p)
+	return p.Spec.NodeName == "" &&
```
Comment (ellistarn) [inline pkg/controllers/selection/controller.go:107]:
```suggestion
	return !pod.IsScheduled(p) &&
```

File: pkg/controllers/selection/controller.go [hunk 2]
```diff
@@ -104,7 +104,12 @@ func (c *Controller) selectProvisioner(ctx context.Context, pod *v1.Pod) (errs e
...
+		p.Status.NominatedNodeName == "" &&
```
Comment (ellistarn) [inline pkg/controllers/selection/controller.go:108]: Thoughts on making a help pod.IsPreempting(pod) to encapsulate this?

**Comment by ellistarn** [comment]
Looks like nominatednodename will be cleared if the pod fails to preempt another pod (e.g. another pod is scheduled). https://kubernetes.io/docs/concepts/scheduling-eviction/pod-priority-preemption/#user-exposed-information. This should work quite nicely.

**Review by ellistarn — APPROVED** [review]

**Comment by ellistarn** [comment]
Thanks!
