### PR TITLE
fix: AWSNodeTemplate controller should not produce an error if no securityGroupSelector is specified

### LINKED ISSUE #3435: Security group discover fail when using launchTemplate in AWSNodeTemplate
### Version

Karpenter Version: 0.25.0
Kubernetes Version: v1.23.14-eks-ffeb93d

### Expected Behavior

While using launchTemplate, I expect karpenter controller to discover the security groups, either by taking it from launch template itself, or discover it by default  `kubernetes.io/cluster/<clustername>` tag. The subnet discovery works as usual. 

Karpenter v0.22.1 didn't show this error, but v0.24.0 and v0.25.0 both do.

### Actual Behavior

Controller shows the following error repeatedly

```
2023-02-21T22:43:08.810Z	ERROR	controller	Reconciler error	{"commit": "beb0a64-dirty", "controller": "awsnodetemplate", "controllerGroup": "karpenter.k8s.aws", "controllerKind": "AWSNodeTemplate", "AWSNodeTemplate": {"name":"awslinux2"}, "namespace": "", "name": "awslinux2", "reconcileID": "2de7cfc8-07f4-4c7e-88a8-98ee45b4ad6e", "error": "describing security groups [], InvalidParameterValue: The filter 'null' is invalid
\tstatus code: 400, request id: e46a6816-a666-4139-851a-7f5c4ed52d65"}
```
**The nodes are being launched, though**

### Steps to Reproduce the Problem

1) install/upgrade to karpenter 0.24.0+
2) apply the manifest

### Resource Specs and Logs

Node template I use:
```apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  annotations:
    meta.helm.sh/release-name: rokt-karpenter
    meta.helm.sh/release-namespace: karpenter
  labels:
    app.kubernetes.io/managed-by: Helm
  name: awslinux2
spec:
  launchTemplate: NodeLaunchTemplate_xxxxx
  subnetSelector:
    Name: '*-app-*'
    kubernetes.io/cluster/dev-eks: shared
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by engedaam**
Fixes #3435

**Description**
Karpenter produces an error when the securityGroupSelector is not present, however a launchTemplate is present. As karpenter detects securityGroups from launchTemplates there should not be an error. 

**How was this change tested?**
Manuel testing
*

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

File: pkg/providers/securitygroup/securitygroup.go [hunk 1]
```diff
@@ -55,7 +55,11 @@ func (p *Provider) List(ctx context.Context, nodeTemplate *v1alpha1.AWSNodeTempl
 	p.Lock()
 	defer p.Unlock()
 	// Get SecurityGroups
-	securityGroups, err := p.getSecurityGroups(ctx, p.getFilters(nodeTemplate))
+	filters := p.getFilters(nodeTemplate)
```
Comment (ellistarn) [inline pkg/providers/securitygroup/securitygroup.go:58]: Can you throw a TODO to revisit this for #1327, where we're removing custom LTs and security group will be required.

File: pkg/providers/securitygroup/securitygroup.go [hunk 2]
```diff
@@ -55,7 +55,13 @@ func (p *Provider) List(ctx context.Context, nodeTemplate *v1alpha1.AWSNodeTempl
 	p.Lock()
 	defer p.Unlock()
 	// Get SecurityGroups
-	securityGroups, err := p.getSecurityGroups(ctx, p.getFilters(nodeTemplate))
+	// TODO: When removing custom launchTemplates for v1beta1, security groups will be required.
+	// The check will not be necessary
+	filters := p.getFilters(nodeTemplate)
+	if len(filters) == 0 {
```
Comment (jonathan-innis) [inline pkg/providers/securitygroup/securitygroup.go:61]: This seems reasonable but I would expect the same behavior for subnet provider as well; otherwise, the divergent behavior is going to get confusing

File: pkg/controllers/machine/link/suite_test.go [hunk 3]
```diff
@@ -108,7 +108,12 @@ var _ = Describe("MachineLink", func() {
 		ec2API.Reset()
 		instanceID = fake.InstanceID()
 		providerID = fmt.Sprintf("aws:///test-zone-1a/%s", instanceID)
-		nodeTemplate = test.AWSNodeTemplate(v1alpha1.AWSNodeTemplateSpec{})
+		nodeTemplate = test.AWSNodeTemplate(v1alpha1.AWSNodeTemplateSpec{
```
Comment (jonathan-innis) [inline pkg/controllers/machine/link/suite_test.go:111]: Any thought to just making this the test default?

**Comment by jonathan-innis** [comment]
We should add an AWSNodeTemplate controller test that ensures that we don't error on reconcile now, that way we make sure that we hold the bar when there is no securityGroupSelector

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀
