### PR TITLE
fix: query for both forms of Linux/Unix OS on spot

### LINKED ISSUE #2568: EC2 Spot instance using generation 1-3 only
### Version

__Karpenter Version:__ v0.16.1

__Kubernetes Version:__ v1.23.9
region: us-east-1

### Expected Behavior

Create spot instances generation 4-6

### Actual Behavior

When I’m using spot instance karpenter found only gen 3, when I hardcoded to use another gen, it shows an error like
```
2022-09-28T13:31:17.842Z	ERROR	controller.provisioning	Could not schedule pod, incompatible with provisioner "spot", no instance type satisfied resources {"cpu":"1","pods":"1"} and requirements karpenter.k8s.aws/instance-family In [c4 m4 m5 m5a m6a and 3 others], karpenter.sh/capacity-type In [spot], kubernetes.io/arch In [amd64], karpenter.sh/provisioner-name In [spot]	{"commit": "5d4ae35-dirty", "pod": "kube-system/inflate-69f485d6c8-6nw8q"
```

### Steps to Reproduce the Problem

```yaml
---
apiVersion: karpenter.sh/v1alpha5
kind: Provisioner
metadata:
  name: spot
spec:
  requirements:
    - key: node.kubernetes.io/instance-type
      operator: In
      values:
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - c5.large
      - c5.xlarge
      - c5a.large
      - c5a.xlarge
      - r5.large
      - r5.xlarge    
    - key: "karpenter.sh/capacity-type"
      operator: In
      values: ["spot"]
  limits:
    resources:
      cpu: 1000
  providerRef:
    name: spot
  ttlSecondsAfterEmpty: 120
---
apiVersion: karpenter.k8s.aws/v1alpha1
kind: AWSNodeTemplate
metadata:
  name: spot
spec:
  amiFamily: Custom
  amiSelector:
    aws-ids: my-custom
  subnetSelector:                          
    karpenter.sh/discovery: e2e
  securityGroupSelector:                      
    karpenter.sh/discovery: e2e
  instanceProfile: ""
```
deployment
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inflate
spec:
  replicas: 0
  selector:
    matchLabels:
      app: inflate
  template:
    metadata:
      labels:
        app: inflate
    spec:
      terminationGracePeriodSeconds: 0
      containers:
        - name: inflate
          image: public.ecr.aws/eks-distro/kubernetes/pause:3.2
          resources:
            requests:
              cpu: 1
      nodeSelector:              
        karpenter.sh/capacity-type: spot
```
```sh
k scale deployment --replicas 2 inflate
```

### Resource Specs and Logs

when I'm using version 0.16.0 all is ok
```
2022-09-29T11:20:48.441Z	INFO	controller.provisioning	Found 1 provisionable pod(s)	{"commit": "639756a"}
2022-09-29T11:20:48.441Z	INFO	controller.provisioning	Computed 1 new node(s) will fit 1 pod(s)	{"commit": "639756a"}
2022-09-29T11:20:48.441Z	INFO	controller.provisioning	Launching node with 1 pods requesting {"cpu":"1445m","memory":"651Mi","pods":"7"} from types c5a.large, c5.large, m5.large, r5.large, c5a.xlarge and 4 other(s)	{"commit": "639756a", "provisioner": "spot"}
2022-09-29T11:20:48.660Z	DEBUG	controller.provisioning.cloudprovider	Discovered security groups: [sg-00dbdc80a8747f4d0]	{"commit": "639756a", "provisioner": "spot"}
2022-09-29T11:20:48.670Z	DEBUG	controller.provisioning.cloudprovider	Discovered kubernetes version 1.23	{"commit": "639756a", "provisioner": "spot"}
2022-09-29T11:20:48.715Z	DEBUG	controller.provisioning.cloudprovider	Discovered images: [ami-03722da6062481565]	{"commit": "639756a", "provisioner": "spot"}
2022-09-29T11:20:51.868Z	INFO	controller.provisioning.cloudprovider	Launched instance: i-0d6205de49a9a93da, hostname: ip-10-255-255-38.ec2.internal, type: r5.large, zone: us-east-1b, capacityType: spot	{"commit": "639756a", "provisioner": "spot"}
```

when version 0.16.1 - 0.16.3
```
2022-09-29T11:25:01.349Z	ERROR	controller.provisioning	Could not schedule pod, incompatible with provisioner "spot", no instance type satisfied resources {"cpu":"1","pods":"1"} and requirements karpenter.sh/capacity-type In [spot], kubernetes.io/arch In [amd64], karpenter.sh/provisioner-name In [spot], node.kubernetes.io/instance-type In [c5.large c5.xlarge c5a.large c5a.xlarge m5.2xlarge and 4 others]	{"commit": "b157d45", "pod": "kube-system/inflate-69f485d6c8-9pqlh"}
2022-09-29T11:25:06.311Z	ERROR	controller.provisioning	Could not schedule pod, incompatible with provisioner "spot", no instance type satisfied resources {"cpu":"1","pods":"1"} and requirements karpenter.sh/provisioner-name In [spot], node.kubernetes.io/instance-type In [c5.large c5.xlarge c5a.large c5a.xlarge m5.2xlarge and 4 others], karpenter.sh/capacity-type In [spot], kubernetes.io/arch In [amd64]	{"commit": "b157d45", "pod": "kube-system/inflate-69f485d6c8-9pqlh"}
```

any other issues aren't shown up

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### PR DESCRIPTION
**Pull request by tzneal**
Fixes #2568 

**Description**

Depending on account settings, instances may be listed under one of two product descriptions.  We should query for them both to ensure we don't fail to launch spot instances.

**How was this change tested?**

- Unit testing
- Deployed to EKS and verified that my spot instance prices were still fetched.

**Does this change impact docs?**
- [ ] Yes, PR includes docs updates
- [ ] Yes, issue opened: # 
- [ ] No

**Release Note**

```release-note

```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

### CODE REVIEW

**Review by jonathan-innis — DISMISSED** [review]
LGTM 🚀

File: pkg/cloudproviders/aws/cloudprovider/pricing_test.go [hunk 1]
```diff
@@ -175,4 +176,28 @@ var _ = Describe("Pricing", func() {
 		_, ok := p.SpotPrice("c99.large", "test-zone-1b")
 		Expect(ok).To(BeFalse())
 	})
+	It("should query for  `Linux/UNIX` and `Linux/UNIX (Amazon VPC)`", func() {
```
Comment (ellistarn) [inline pkg/cloudproviders/aws/cloudprovider/pricing_test.go:179]: Can you drop in a comment about what case this covers (e.g. EC2 Classic)
```suggestion
	It("should query for `Linux/UNIX` and `Linux/UNIX (Amazon VPC)`", func() {
```

**Review by ellistarn — DISMISSED** [review]

**Review by jonathan-innis — APPROVED** [review]
LGTM 🚀
